---
name: Build and Deploy Next.js App to CloudFront
on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: ${{ secrets.BUCKET }}
      REGION: ${{ secrets.REGION }}
      DIST_ID: ${{ secrets.DIST_ID }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Install Dependencies
      run: npm install

    - name: Build website
      run: npm run build

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync ./out s3://${{ secrets.BUCKET }}/

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.DIST_ID }} \
          --paths "/*"