---
name: Build and Deploy Next.js App to CloudFront
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: www.codecrush.link
      REGION: eu-central-1
      DIST_ID: E1VR35XVV7IPQD

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    - name: Install Dependencies
      run: npm install

    - name: Build Static Website
      run: npm run export

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 cp --recursive --acl public-read out/ s3://${{ env.BUCKET }}/

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"